# Generated by Django 2.2 on 2020-01-28 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200128_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='main_image',
            field=models.ImageField(upload_to=''),
        ),
    ]
