# Generated by Django 2.2.10 on 2020-02-16 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='comaprison',
            new_name='comparison',
        ),
    ]
