# Generated by Django 2.2 on 2020-01-28 19:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='current_affair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
                ('postedon', models.DateField(auto_now_add=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='current_affair_categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('keywords', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Current Affairs Categories',
            },
        ),
        migrations.CreateModel(
            name='previous_year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_type', models.CharField(choices=[('E', 'Exam'), ('R', 'Result')], max_length=1)),
                ('year', models.IntegerField()),
                ('questions', models.FileField(upload_to='')),
                ('answers', models.FileField(upload_to='')),
            ],
            options={
                'verbose_name_plural': 'Previous Year Questions/Answers',
            },
        ),
        migrations.CreateModel(
            name='current_affairs_uplifts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_affair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.current_affair')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='current_affairs_likes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_affair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.current_affair')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='current_affair',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.current_affair_categories'),
        ),
        migrations.AddField(
            model_name='current_affair',
            name='postedby',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('comment_text', models.TextField()),
                ('current_affair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_affair', to='exams.current_affair')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_affair_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
