# Generated by Django 2.2.9 on 2020-01-29 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_auto_20200130_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='previous_year',
            name='answers',
            field=models.FileField(upload_to='previous_years'),
        ),
        migrations.AlterField(
            model_name='previous_year',
            name='exam_type',
            field=models.CharField(choices=[('S', 'SSC'), ('U', 'UPSC')], max_length=1),
        ),
        migrations.AlterField(
            model_name='previous_year',
            name='questions',
            field=models.FileField(upload_to='previous_years'),
        ),
    ]
