# Generated by Django 2.2.9 on 2020-02-05 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_auto_20200130_0121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='current_affairs_likes',
            name='current_affair',
        ),
        migrations.RemoveField(
            model_name='current_affairs_likes',
            name='user',
        ),
        migrations.RemoveField(
            model_name='current_affairs_uplifts',
            name='current_affair',
        ),
        migrations.RemoveField(
            model_name='current_affairs_uplifts',
            name='user',
        ),
        migrations.RemoveField(
            model_name='current_affair',
            name='category',
        ),
        migrations.RemoveField(
            model_name='current_affair',
            name='description',
        ),
        migrations.RemoveField(
            model_name='current_affair',
            name='postedby',
        ),
        migrations.RemoveField(
            model_name='current_affair',
            name='postedon',
        ),
        migrations.AddField(
            model_name='current_affair',
            name='file',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='current_affair',
            name='month',
            field=models.CharField(choices=[('Jan', 'January'), ('Feb', 'February'), ('Mar', 'March'), ('Apr', 'April'), ('May', 'May'), ('Jun', 'June'), ('Jul', 'July'), ('Aug', 'August'), ('Sep', 'September'), ('Oct', 'October'), ('Nov', 'November'), ('Dec', 'December')], default=1, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='current_affair',
            name='year',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='comment',
        ),
        migrations.DeleteModel(
            name='current_affair_categories',
        ),
        migrations.DeleteModel(
            name='current_affairs_likes',
        ),
        migrations.DeleteModel(
            name='current_affairs_uplifts',
        ),
    ]
